### ISSUE TITLE
依赖安装报错

### ISSUE THREAD

**Issue by 68minv** [wrenfairbank/telegram_gcloner#2]
`Using cached https://files.pythonhosted.org/packages/95/84/119a46d494f008969bf0c775cb2c6b3579d3c4cc1bb1b41a022aa93ee242/tornado-6.0.4.tar.gz’`
    `Complete output from command python setup.py egg_info:`
    `Traceback (most recent call last):`
      `File "<string>", line 1, in <module>`
    `ModuleNotFoundError: No module named 'setuptools'`
  ` ----------------------------------------`
 `Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-qg52qadt/tornado/`

**Comment by wrenfairbank** [comment]
Not relevant to project.
